Update instancesPreview.py
LettError/designSpaceRoboFontExtension pull request #54
Opened 2023-08-29 20:18 UTC by connordavenport

Fix DummyFont UPM to scale correctly. I noticed that if the UPM isnt 1000 the line height is really tight in the preview

2023-08-29 20:27 UTC, typemytype commented
True! 1000 is a silly dummy number...

I guess DSE can just pick the highest units per em from all sources:

Your calculations are way to heavy! 

and I guess with the same calculation power it could be the correct interpolated value :) 

```python
# simple example
operator = UFOOperator(path)
operator.loadFonts()

# get the biggest ump
upms = [font.info.unitsPerEm for font in operator.fonts.values()]

if upms:
    upm = max(upms)
else:
    upm = 1000
```

2023-08-29 20:36 UTC, typemytype commented
the correct max value for all instances:

```python

from ufoProcessor.ufoOperator import UFOOperator

# simple example
operator = UFOOperator(path)
operator.loadFonts()


upms = set()
for instance in operator.instances:
    continuousLocation, discreteLocation = operator.splitLocation(instance.location)
    infoMutator = operator.getInfoMutator(discreteLocation)
    info = infoMutator.makeInstance(continuousLocation)
    upms.add(info.unitsPerEm)
# get the biggest ump
if upms:
    upm = max(upms)
else:
    upm = 1000
    
print(upm)```

could you make this change? 

thanks!

2023-08-29 20:45 UTC, connordavenport commented
Oh woah thats good to know that you dont need to open the sources to get the value! Yup, I will update

2023-08-29 20:52 UTC, connordavenport commented
Code has been updated as per your recommendations!

2023-08-29 20:56 UTC, typemytype requested changes

2023-08-29 20:56 UTC, typemytype commented on DesignspaceEditor2.roboFontExt/lib/designspaceEditor/instancesPreview.py
> +        dummyFont.info.unitsPerEm = upm
this could be a single line
directly setting the value in the info object

2023-08-29 21:00 UTC, typemytype commented on DesignspaceEditor2.roboFontExt/lib/designspaceEditor/instancesPreview.py
> +        dummyFont.info.unitsPerEm = upm
minor thingy :) thanks

2023-08-30 08:07 UTC, merged

2023-08-30 08:07 UTC, typemytype commented
thanks!!